server_cert: /Users/macbook/.disney/127.0.0.1.crt
server_key: /Users/macbook/.disney/127.0.0.1.key
ca_cert: /Users/macbook/.disney/disneyland.crt
listen_on: :50051
db_uri: postgres://localhost/disneyland?sslmode=disable
